// This file is auto-generated by @hey-api/openapi-ts

export const AuthorInputSchema = {
    properties: {
        person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Person Id'
        },
        is_corresponding: {
            type: 'boolean',
            title: 'Is Corresponding',
            default: false
        }
    },
    type: 'object',
    required: ['person_id'],
    title: 'AuthorInput'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DecisionCreateSchema = {
    properties: {
        paper_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Version Id'
        },
        decision: {
            '$ref': '#/components/schemas/DecisionType'
        },
        rationale: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rationale'
        }
    },
    type: 'object',
    required: ['paper_version_id', 'decision'],
    title: 'DecisionCreate'
} as const;

export const DecisionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        paper_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Version Id'
        },
        decision: {
            '$ref': '#/components/schemas/DecisionType'
        },
        rationale: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rationale'
        },
        decided_at: {
            type: 'string',
            format: 'date-time',
            title: 'Decided At'
        }
    },
    type: 'object',
    required: ['id', 'paper_version_id', 'decision', 'rationale', 'decided_at'],
    title: 'DecisionPublic'
} as const;

export const DecisionTypeSchema = {
    type: 'string',
    enum: ['accept', 'reject', 'revise'],
    title: 'DecisionType'
} as const;

export const DeskDecisionCreateSchema = {
    properties: {
        paper_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Id'
        },
        decision: {
            '$ref': '#/components/schemas/DeskDecisionType'
        },
        rationale: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rationale'
        }
    },
    type: 'object',
    required: ['paper_id', 'decision'],
    title: 'DeskDecisionCreate'
} as const;

export const DeskDecisionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        paper_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Id'
        },
        decision: {
            '$ref': '#/components/schemas/DeskDecisionType'
        },
        rationale: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rationale'
        },
        decided_at: {
            type: 'string',
            format: 'date-time',
            title: 'Decided At'
        }
    },
    type: 'object',
    required: ['id', 'paper_id', 'decision', 'rationale', 'decided_at'],
    title: 'DeskDecisionPublic'
} as const;

export const DeskDecisionTypeSchema = {
    type: 'string',
    enum: ['proceed', 'reject'],
    title: 'DeskDecisionType'
} as const;

export const EditorAssignmentCreateSchema = {
    properties: {
        paper_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Id'
        },
        editor_person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Editor Person Id'
        }
    },
    type: 'object',
    required: ['paper_id', 'editor_person_id'],
    title: 'EditorAssignmentCreate'
} as const;

export const EditorAssignmentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        paper_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Id'
        },
        editor_person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Editor Person Id'
        },
        assigned_at: {
            type: 'string',
            format: 'date-time',
            title: 'Assigned At'
        }
    },
    type: 'object',
    required: ['id', 'paper_id', 'editor_person_id', 'assigned_at'],
    title: 'EditorAssignmentPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PaperPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Title'
        },
        abstract: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Abstract'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        resubmission_of_paper_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resubmission Of Paper Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'created_at', 'resubmission_of_paper_id'],
    title: 'PaperPublic'
} as const;

export const PaperSubmissionSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Title'
        },
        abstract: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Abstract'
        },
        pdf_url: {
            type: 'string',
            maxLength: 2000,
            title: 'Pdf Url'
        },
        authors: {
            items: {
                '$ref': '#/components/schemas/AuthorInput'
            },
            type: 'array',
            minItems: 1,
            title: 'Authors'
        }
    },
    type: 'object',
    required: ['title', 'pdf_url', 'authors'],
    title: 'PaperSubmission',
    description: 'Input for submitting a new paper with its first version and authors.'
} as const;

export const PapersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PaperPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PapersPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReviewCreateSchema = {
    properties: {
        assignment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Assignment Id'
        },
        content: {
            type: 'string',
            maxLength: 50000,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['assignment_id', 'content'],
    title: 'ReviewCreate'
} as const;

export const ReviewPublicSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 50000,
            title: 'Content'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        assignment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Assignment Id'
        },
        submitted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Submitted At'
        }
    },
    type: 'object',
    required: ['content', 'id', 'assignment_id', 'submitted_at'],
    title: 'ReviewPublic'
} as const;

export const ReviewerAssignmentCreateSchema = {
    properties: {
        paper_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Version Id'
        },
        reviewer_person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewer Person Id'
        },
        identity_confidential: {
            type: 'boolean',
            title: 'Identity Confidential',
            default: false
        }
    },
    type: 'object',
    required: ['paper_version_id', 'reviewer_person_id'],
    title: 'ReviewerAssignmentCreate'
} as const;

export const ReviewerAssignmentPublicSchema = {
    properties: {
        identity_confidential: {
            type: 'boolean',
            title: 'Identity Confidential',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        paper_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Version Id'
        },
        reviewer_person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewer Person Id'
        },
        status: {
            '$ref': '#/components/schemas/ReviewerAssignmentStatus'
        },
        invited_at: {
            type: 'string',
            format: 'date-time',
            title: 'Invited At'
        }
    },
    type: 'object',
    required: ['id', 'paper_version_id', 'reviewer_person_id', 'status', 'invited_at'],
    title: 'ReviewerAssignmentPublic'
} as const;

export const ReviewerAssignmentStatusSchema = {
    type: 'string',
    enum: ['invited', 'accepted', 'declined', 'completed'],
    title: 'ReviewerAssignmentStatus'
} as const;

export const ReviewerAssignmentUpdateSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ReviewerAssignmentStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ReviewerAssignmentUpdate'
} as const;

export const ReviewerAssignmentWithPaperSchema = {
    properties: {
        identity_confidential: {
            type: 'boolean',
            title: 'Identity Confidential',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        paper_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Version Id'
        },
        reviewer_person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewer Person Id'
        },
        status: {
            '$ref': '#/components/schemas/ReviewerAssignmentStatus'
        },
        invited_at: {
            type: 'string',
            format: 'date-time',
            title: 'Invited At'
        },
        paper_title: {
            type: 'string',
            title: 'Paper Title'
        },
        paper_id: {
            type: 'string',
            format: 'uuid',
            title: 'Paper Id'
        }
    },
    type: 'object',
    required: ['id', 'paper_version_id', 'reviewer_person_id', 'status', 'invited_at', 'paper_title', 'paper_id'],
    title: 'ReviewerAssignmentWithPaper'
} as const;

export const ReviewerAssignmentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReviewerAssignmentWithPaper'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReviewerAssignmentsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        person_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;