// This file is auto-generated by @hey-api/openapi-ts

export type AuthorInput = {
    person_id: string;
    is_corresponding?: boolean;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DecisionCreate = {
    paper_version_id: string;
    decision: DecisionType;
    rationale?: (string | null);
};

export type DecisionPublic = {
    id: string;
    paper_version_id: string;
    decision: DecisionType;
    rationale: (string | null);
    decided_at: string;
};

export type DecisionType = 'accept' | 'reject' | 'revise';

export type DeskDecisionCreate = {
    paper_id: string;
    decision: DeskDecisionType;
    rationale?: (string | null);
};

export type DeskDecisionPublic = {
    id: string;
    paper_id: string;
    decision: DeskDecisionType;
    rationale: (string | null);
    decided_at: string;
};

export type DeskDecisionType = 'proceed' | 'reject';

export type EditorAssignmentCreate = {
    paper_id: string;
    editor_person_id: string;
};

export type EditorAssignmentPublic = {
    id: string;
    paper_id: string;
    editor_person_id: string;
    assigned_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PaperPublic = {
    title: string;
    abstract?: (string | null);
    id: string;
    created_at: string;
    resubmission_of_paper_id: (string | null);
};

export type PapersPublic = {
    data: Array<PaperPublic>;
    count: number;
};

/**
 * Input for submitting a new paper with its first version and authors.
 */
export type PaperSubmission = {
    title: string;
    abstract?: (string | null);
    pdf_url: string;
    authors: Array<AuthorInput>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReviewCreate = {
    assignment_id: string;
    content: string;
};

export type ReviewerAssignmentCreate = {
    paper_version_id: string;
    reviewer_person_id: string;
    identity_confidential?: boolean;
};

export type ReviewerAssignmentPublic = {
    identity_confidential?: boolean;
    id: string;
    paper_version_id: string;
    reviewer_person_id: string;
    status: ReviewerAssignmentStatus;
    invited_at: string;
};

export type ReviewerAssignmentStatus = 'invited' | 'accepted' | 'declined' | 'completed';

export type ReviewerAssignmentUpdate = {
    status?: (ReviewerAssignmentStatus | null);
};

export type ReviewPublic = {
    content: string;
    id: string;
    assignment_id: string;
    submitted_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    person_id?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PapersSubmitPaperData = {
    requestBody: PaperSubmission;
};

export type PapersSubmitPaperResponse = (PaperPublic);

export type PapersListPapersData = {
    limit?: number;
    skip?: number;
};

export type PapersListPapersResponse = (PapersPublic);

export type PapersGetPaperData = {
    paperId: string;
};

export type PapersGetPaperResponse = (PaperPublic);

export type PapersAssignEditorData = {
    paperId: string;
    requestBody: EditorAssignmentCreate;
};

export type PapersAssignEditorResponse = (EditorAssignmentPublic);

export type PapersMakeDeskDecisionData = {
    paperId: string;
    requestBody: DeskDecisionCreate;
};

export type PapersMakeDeskDecisionResponse = (DeskDecisionPublic);

export type PapersInviteReviewerData = {
    paperId: string;
    requestBody: ReviewerAssignmentCreate;
    versionId: string;
};

export type PapersInviteReviewerResponse = (ReviewerAssignmentPublic);

export type PapersMakeDecisionData = {
    paperId: string;
    requestBody: DecisionCreate;
    versionId: string;
};

export type PapersMakeDecisionResponse = (DecisionPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ReviewerAssignmentsRespondToInvitationData = {
    assignmentId: string;
    requestBody: ReviewerAssignmentUpdate;
};

export type ReviewerAssignmentsRespondToInvitationResponse = (ReviewerAssignmentPublic);

export type ReviewerAssignmentsSubmitReviewData = {
    assignmentId: string;
    requestBody: ReviewCreate;
};

export type ReviewerAssignmentsSubmitReviewResponse = (ReviewPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);