"""add editor and reviewer workflow models

Revision ID: 355c4d4ee0bd
Revises: 7209d1eefaae
Create Date: 2025-12-31 23:25:44.419666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '355c4d4ee0bd'
down_revision = '7209d1eefaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deskdecision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('proceed', 'reject', name='deskdecisiontype'), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deskdecision_paper_id'), 'deskdecision', ['paper_id'], unique=False)
    op.create_table('editorassignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('editor_person_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['editor_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorassignment_editor_person_id'), 'editorassignment', ['editor_person_id'], unique=False)
    op.create_index(op.f('ix_editorassignment_paper_id'), 'editorassignment', ['paper_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_version_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('accept', 'reject', 'revise', name='decisiontype'), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paperversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_paper_version_id'), 'decision', ['paper_version_id'], unique=False)
    op.create_table('reviewerassignment',
    sa.Column('identity_confidential', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_version_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_person_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'accepted', 'declined', 'completed', name='reviewerassignmentstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paperversion.id'], ),
    sa.ForeignKeyConstraint(['reviewer_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewerassignment_paper_version_id'), 'reviewerassignment', ['paper_version_id'], unique=False)
    op.create_index(op.f('ix_reviewerassignment_reviewer_person_id'), 'reviewerassignment', ['reviewer_person_id'], unique=False)
    op.create_table('review',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=50000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['reviewerassignment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_index(op.f('ix_reviewerassignment_reviewer_person_id'), table_name='reviewerassignment')
    op.drop_index(op.f('ix_reviewerassignment_paper_version_id'), table_name='reviewerassignment')
    op.drop_table('reviewerassignment')
    op.drop_index(op.f('ix_decision_paper_version_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_editorassignment_paper_id'), table_name='editorassignment')
    op.drop_index(op.f('ix_editorassignment_editor_person_id'), table_name='editorassignment')
    op.drop_table('editorassignment')
    op.drop_index(op.f('ix_deskdecision_paper_id'), table_name='deskdecision')
    op.drop_table('deskdecision')
    # ### end Alembic commands ###
