"""add indexes on paper FK columns

Revision ID: 7209d1eefaae
Revises: abe4d84bd815
Create Date: 2025-12-31 23:24:13.081910

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7209d1eefaae'
down_revision = 'abe4d84bd815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_paperauthor_person_id'), 'paperauthor', ['person_id'], unique=False)
    op.create_index(op.f('ix_paperversion_paper_id'), 'paperversion', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paperversion_paper_id'), table_name='paperversion')
    op.drop_index(op.f('ix_paperauthor_person_id'), table_name='paperauthor')
    # ### end Alembic commands ###
