"""add paper models

Revision ID: abe4d84bd815
Revises: 3f761deda2d0
Create Date: 2025-12-31 23:21:51.208126

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abe4d84bd815'
down_revision = '3f761deda2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resubmission_of_paper_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resubmission_of_paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paperauthor',
    sa.Column('author_position', sa.Integer(), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'person_id')
    )
    op.create_table('paperversion',
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paperversion')
    op.drop_table('paperauthor')
    op.drop_table('paper')
    # ### end Alembic commands ###
